name = input("What's your name? ")
age = input("Enter age: ")
job = input("Whats your dream job? ")
message = input("message to the world: ")

print("==========================")
print("about user")
print("==========================")
print("Hi! my name is, ", name )
print("i am ", (age), "  years old")
print("My dream job is ", job)
print("Message: ")
print(message)
print("==========================")